import { DataType, DataTypeDefinition, DataTypeInput, ColumnOptions, isTextType } from '../data-types';
import { sanitizeIdentifier } from '../sql-utils';
import { ForeignKeyModelSpec, ReferentialAction } from './types';

const DEFAULT_VARCHAR = 255;

/**
 * Tipo SQL Firebird 3+ para a coluna (CREATE TABLE / ADD COLUMN best-effort).
 */
export function columnTypeToDdl(type: DataTypeInput): string {
    if (typeof type === 'object' && type !== null && 'sql' in (type as DataTypeDefinition)) {
        return (type as DataTypeDefinition).sql;
    }

    const t = type as string;

    if (t === DataType.STRING || t === 'VARCHAR') {
        return `VARCHAR(${DEFAULT_VARCHAR})`;
    }
    if (t === DataType.CHAR) {
        return 'CHAR(1)';
    }
    if (t === DataType.SMALLINT) return 'SMALLINT';
    if (t === DataType.INTEGER) return 'INTEGER';
    if (t === DataType.BIGINT) return 'BIGINT';
    if (t === DataType.BOOLEAN) return 'BOOLEAN';
    if (t === DataType.DATE || t === DataType.DATEONLY) return 'DATE';
    if (t === DataType.TIME) return 'TIME';
    if (t === DataType.TIMESTAMP) return 'TIMESTAMP';
    if (t === DataType.FLOAT) return 'FLOAT';
    if (t === 'DOUBLE PRECISION' || t === DataType.DOUBLE) return 'DOUBLE PRECISION';
    if (t === DataType.NUMERIC) return 'NUMERIC(18,0)';
    if (t === DataType.DECIMAL) return 'DECIMAL(18,2)';
    if (t === DataType.TEXT || t === 'BLOB_TEXT' || isTextType(type as DataTypeInput)) {
        return 'BLOB SUB_TYPE TEXT';
    }
    if (t === DataType.BINARY || t === 'BLOB_BIN' || t === 'BINARY') {
        return 'BLOB';
    }
    if (t === 'ENUM' || t === DataType.ENUM) {
        return 'VARCHAR(255)';
    }
    if (t === 'BLOB') {
        return 'BLOB';
    }

    return t;
}

function formatDefaultValue(column: ColumnOptions, raw: any): string | null {
    if (raw === undefined) return null;
    if (typeof raw === 'function') return null;
    if (raw === null) return 'NULL';
    if (typeof raw === 'number' || typeof raw === 'boolean') {
        return String(raw);
    }
    if (typeof raw === 'string') {
        const escaped = raw.replace(/'/g, "''");
        return `'${escaped}'`;
    }
    if (raw instanceof Date) {
        return `'${raw.toISOString().replace('T', ' ').replace(/\.\d{3}Z$/, '')}'`;
    }
    return null;
}

/**
 * Gera a linha de coluna para CREATE TABLE, sem a vírgula final.
 * identity: se true e primaryKey+autoIncrement, emite `GENERATED BY DEFAULT AS IDENTITY` (FB 3+).
 */
export function columnOptionsToDdl(
    colName: string,
    column: ColumnOptions,
    options: { useIdentity?: boolean } = {}
): string {
    const name = sanitizeIdentifier(colName, 'column');
    const useIdentity = options.useIdentity && column.primaryKey && column.autoIncrement;
    const sqlType = columnTypeToDdl(column.type);
    const parts: string[] = [];

    if (useIdentity) {
        parts.push(`${name} ${sqlType} NOT NULL GENERATED BY DEFAULT AS IDENTITY`);
    } else {
        const partsInner: string[] = [`${name} ${sqlType}`];
        if (column.primaryKey) {
            partsInner.push('NOT NULL');
        } else if (column.allowNull === false) {
            partsInner.push('NOT NULL');
        }
        parts.push(partsInner.join(' '));
    }

    if (!useIdentity) {
        const d = formatDefaultValue(column, column.defaultValue);
        if (d !== null) {
            parts[parts.length - 1] += ` DEFAULT ${d}`;
        }
    }

    if (column.unique && !column.primaryKey) {
        /* UNIQUE como constraint nomeado num 2º passo é mais fácil; inline UNIQUE coluna. */
        parts[parts.length - 1] += ' UNIQUE';
    }

    return parts[0]!;
}

export function primaryKeyColumnNames(
    attrKeys: string[],
    schema: Record<string, ColumnOptions>
): string[] {
    const pks = Object.entries(schema)
        .filter(([, c]) => c.primaryKey)
        .map(([k]) => k);
    if (pks.length) return pks;
    return attrKeys.length ? [attrKeys[0]!] : [];
}

/**
 * CREATE TABLE: colunas + PK. FKs vêm em `ALTER TABLE` separado (Fase 2 do sync).
 */
export function buildCreateTableDdl(
    tableName: string,
    attrKeys: string[],
    schema: Record<string, ColumnOptions>,
    options: { useIdentity: boolean } = { useIdentity: true }
): string {
    const t = sanitizeIdentifier(tableName, 'table');
    const lines: string[] = [];
    for (const key of attrKeys) {
        const col = schema[key]!;
        const line = columnOptionsToDdl(key, col, { useIdentity: options.useIdentity });
        lines.push(line);
    }
    const pkNames = primaryKeyColumnNames(attrKeys, schema);
    if (pkNames.length) {
        const pkList = pkNames.map((k) => sanitizeIdentifier(k, 'column')).join(', ');
        lines.push(`CONSTRAINT ${sanitizeIdentifier(`PK_${t}`, 'constraint')} PRIMARY KEY (${pkList})`);
    }
    return `CREATE TABLE ${t} (\n  ${lines.join(',\n  ')}\n)`;
}

/**
 * `ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY ...` (coluna simples).
 */
export function buildForeignKeyConstraintDdl(
    childTable: string,
    fks: ForeignKeyModelSpec[]
): string {
    const t = sanitizeIdentifier(childTable, 'table');
    if (!fks.length) return '';
    if (fks.length !== 1) {
        throw new Error('FK composta: use múltiplas instruções ALTER (ainda não em batch neste generator).');
    }
    const f = fks[0]!;
    const cname = sanitizeIdentifier(f.constraintName, 'constraint');
    const cref = sanitizeIdentifier(f.childField, 'column');
    const ptab = sanitizeIdentifier(f.parentTable, 'table');
    const pfield = sanitizeIdentifier(f.parentField, 'column');
    const od = (f.onDelete && normalizeAction(f.onDelete)) || 'NO ACTION';
    const ou = (f.onUpdate && normalizeAction(f.onUpdate)) || 'NO ACTION';
    return `ALTER TABLE ${t} ADD CONSTRAINT ${cname} FOREIGN KEY (${cref}) REFERENCES ${ptab} (${pfield}) ON UPDATE ${ou} ON DELETE ${od}`;
}

export function getForeignKeySpec(
    childTable: string,
    colName: string,
    col: ColumnOptions,
    orm: { models: Record<string, any> }
): ForeignKeyModelSpec | null {
    if (!col.references) return null;
    const m = (col.references as any).model;
    const nameStr = String(m || '').trim();
    if (!nameStr) {
        return null;
    }
    const refModel = orm.models[nameStr] ?? orm.models[nameStr.toUpperCase()];
    const parentTableName = refModel
        ? (refModel as any).tableName || (refModel as any).name
        : nameStr;
    const parentKey = col.references.key;
    return {
        constraintName: (col.references as any).constraintName || makeFkName(childTable, colName, String(parentTableName), parentKey),
        childTable: sanitizeIdentifier(childTable, 'table'),
        childField: sanitizeIdentifier(colName, 'column'),
        parentTable: sanitizeIdentifier(String(parentTableName), 'table'),
        parentField: sanitizeIdentifier(parentKey, 'column'),
        onDelete: col.onDelete,
        onUpdate: col.onUpdate
    };
}

function makeFkName(child: string, col: string, parent: string, pcol: string): string {
    const key = `FK|${child}|${col}|${parent}|${pcol}`.toUpperCase();
    let h = 0;
    for (let i = 0; i < key.length; i++) h = (h * 33 + key.charCodeAt(i)) | 0;
    const su = h >>> 0;
    return `OriuFK${su.toString(16).toUpperCase().padStart(7, '0')}`;
}

function normalizeAction(a: ReferentialAction): string {
    const s = String(a).trim().toUpperCase();
    if (s === 'RESTRICT' || s === 'NO ACTION') return 'NO ACTION';
    if (s === 'CASCADE' || s === 'SET NULL' || s === 'SET DEFAULT') return s;
    return s || 'NO ACTION';
}

export function specKey(f: { childTable: string; childField: string; parentTable: string; parentField: string }): string {
    return `${f.childTable}|${f.childField}|${f.parentTable}|${f.parentField}`.toUpperCase();
}
