from __future__ import annotations

from datetime import datetime
from typing import Any

from ..data_types import DataType, is_text_type
from .types import ForeignKeyModelSpec, ReferentialAction

DEFAULT_VARCHAR = 255


def sanitize_identifier(value: str, _kind: str = "identifier") -> str:
    raw = str(value or "").strip()
    if not raw:
        raise ValueError("Identifier cannot be empty.")
    if '"' in raw:
        raise ValueError(f'Identifier "{raw}" contains invalid character (\").')
    return raw.upper()


def column_type_to_ddl(data_type: Any) -> str:
    if isinstance(data_type, dict) and "sql" in data_type:
        return str(data_type["sql"])

    t = str(data_type.value if isinstance(data_type, DataType) else data_type or "").upper()
    if t in ("VARCHAR", "STRING"):
        return f"VARCHAR({DEFAULT_VARCHAR})"
    if t == "CHAR":
        return "CHAR(1)"
    if t == "SMALLINT":
        return "SMALLINT"
    if t == "INTEGER":
        return "INTEGER"
    if t == "BIGINT":
        return "BIGINT"
    if t == "BOOLEAN":
        return "BOOLEAN"
    if t in ("DATE", "DATEONLY"):
        return "DATE"
    if t == "TIME":
        return "TIME"
    if t == "TIMESTAMP":
        return "TIMESTAMP"
    if t == "FLOAT":
        return "FLOAT"
    if t in ("DOUBLE PRECISION", "DOUBLE"):
        return "DOUBLE PRECISION"
    if t == "NUMERIC":
        return "NUMERIC(18,0)"
    if t == "DECIMAL":
        return "DECIMAL(18,2)"
    if t in ("TEXT", "BLOB_TEXT") or is_text_type(data_type):
        return "BLOB SUB_TYPE TEXT"
    if t in ("BINARY", "BLOB_BIN", "BLOB_BINARY"):
        return "BLOB"
    if t == "ENUM":
        return "VARCHAR(255)"
    if t == "BLOB":
        return "BLOB"
    return t


def _format_default_value(raw: Any) -> str | None:
    if raw is None:
        return "NULL"
    if raw is ...:
        return None
    if callable(raw):
        return None
    if isinstance(raw, (int, float, bool)):
        return str(raw)
    if isinstance(raw, datetime):
        return f"'{raw.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(raw, str):
        return "'" + raw.replace("'", "''") + "'"
    return None


def column_options_to_ddl(col_name: str, column: dict[str, Any], options: dict[str, Any] | None = None) -> str:
    options = options or {}
    name = sanitize_identifier(col_name, "column")
    use_identity = bool(options.get("use_identity")) and bool(column.get("primaryKey")) and bool(column.get("autoIncrement"))
    sql_type = column_type_to_ddl(column.get("type"))

    if use_identity:
        statement = f"{name} {sql_type} NOT NULL GENERATED BY DEFAULT AS IDENTITY"
    else:
        inner = [f"{name} {sql_type}"]
        if bool(column.get("primaryKey")) or column.get("allowNull") is False:
            inner.append("NOT NULL")
        statement = " ".join(inner)

    if not use_identity:
        default_raw = column["defaultValue"] if "defaultValue" in column else ...
        default_val = _format_default_value(default_raw)
        if default_val is not None:
            statement += f" DEFAULT {default_val}"

    if bool(column.get("unique")) and not bool(column.get("primaryKey")):
        statement += " UNIQUE"

    return statement


def primary_key_column_names(attr_keys: list[str], schema: dict[str, dict[str, Any]]) -> list[str]:
    pks = [name for name, col in schema.items() if bool(col.get("primaryKey"))]
    if pks:
        return pks
    return [attr_keys[0]] if attr_keys else []


def build_create_table_ddl(
    table_name: str,
    attr_keys: list[str],
    schema: dict[str, dict[str, Any]],
    options: dict[str, Any] | None = None,
) -> str:
    options = options or {"use_identity": True}
    table = sanitize_identifier(table_name, "table")
    lines: list[str] = []
    for key in attr_keys:
        line = column_options_to_ddl(key, schema[key], {"use_identity": bool(options.get("use_identity", True))})
        lines.append(line)
    pk_names = primary_key_column_names(attr_keys, schema)
    if pk_names:
        pk_list = ", ".join(sanitize_identifier(col, "column") for col in pk_names)
        lines.append(f"CONSTRAINT {sanitize_identifier(f'PK_{table}', 'constraint')} PRIMARY KEY ({pk_list})")
    return f"CREATE TABLE {table} (\n  " + ",\n  ".join(lines) + "\n)"


def build_foreign_key_constraint_ddl(child_table: str, fks: list[ForeignKeyModelSpec]) -> str:
    table = sanitize_identifier(child_table, "table")
    if not fks:
        return ""
    if len(fks) != 1:
        raise ValueError("Composed FKs are not supported by this helper.")
    fk = fks[0]
    constraint = sanitize_identifier(fk.constraint_name, "constraint")
    child_field = sanitize_identifier(fk.child_field, "column")
    parent_table = sanitize_identifier(fk.parent_table, "table")
    parent_field = sanitize_identifier(fk.parent_field, "column")
    on_delete = normalize_action(fk.on_delete or "NO ACTION")
    on_update = normalize_action(fk.on_update or "NO ACTION")
    return (
        f"ALTER TABLE {table} ADD CONSTRAINT {constraint} FOREIGN KEY ({child_field}) "
        f"REFERENCES {parent_table} ({parent_field}) ON UPDATE {on_update} ON DELETE {on_delete}"
    )


def get_foreign_key_spec(child_table: str, col_name: str, col: dict[str, Any], orm) -> ForeignKeyModelSpec | None:
    refs = col.get("references")
    if not isinstance(refs, dict):
        return None
    model_name = str(refs.get("model") or "").strip()
    if not model_name:
        return None
    ref_model = orm.models.get(model_name) or orm.models.get(model_name.upper())
    parent_table = (
        getattr(ref_model, "tableName", None)
        or getattr(ref_model, "__tablename__", None)
        or getattr(ref_model, "__name__", None)
        or model_name
    )
    parent_key = str(refs.get("key") or "ID")
    constraint = refs.get("constraintName") or make_fk_name(child_table, col_name, str(parent_table), parent_key)
    return ForeignKeyModelSpec(
        constraint_name=sanitize_identifier(str(constraint), "constraint"),
        child_table=sanitize_identifier(child_table, "table"),
        child_field=sanitize_identifier(col_name, "column"),
        parent_table=sanitize_identifier(str(parent_table), "table"),
        parent_field=sanitize_identifier(parent_key, "column"),
        on_delete=col.get("onDelete"),
        on_update=col.get("onUpdate"),
    )


def make_fk_name(child: str, col: str, parent: str, pcol: str) -> str:
    key = f"FK|{child}|{col}|{parent}|{pcol}".upper()
    h = 0
    for ch in key:
        h = ((h * 33) + ord(ch)) & 0xFFFFFFFF
    return f"OriuFK{h:07X}"


def normalize_action(action: ReferentialAction) -> str:
    text = str(action).strip().upper()
    if text in ("RESTRICT", "NO ACTION"):
        return "NO ACTION"
    if text in ("CASCADE", "SET NULL", "SET DEFAULT"):
        return text
    return text or "NO ACTION"


def spec_key(spec: dict[str, str] | ForeignKeyModelSpec) -> str:
    if isinstance(spec, ForeignKeyModelSpec):
        return f"{spec.child_table}|{spec.child_field}|{spec.parent_table}|{spec.parent_field}".upper()
    return f"{spec['child_table']}|{spec['child_field']}|{spec['parent_table']}|{spec['parent_field']}".upper()
