security.db = $(dir_secDb)/security4.fdb
{
RemoteAccess = false
DefaultDbCachePages = 256
}
IOSHUA = D:\base\IOSHUA.FDB
{
DefaultDBCachePages = 524288
LockMemSize = 30M
TempCacheLimit  =2185M
}
SAOFRANCISCO = D:\base\SAOFRANCISCO.FDB
{
    DefaultDBCachePages = 131072
    LockMemSize = 20M
    TempCacheLimit = 1000M
}