from __future__ import annotations

from typing import Any, Dict

from orm_py.base import OriusORM
from orm_py.data_types import DataType, DataTypes


T_ATO_ATTRIBUTES: Dict[str, Dict[str, Any]] = {
    "ATO_ID": {"type": DataTypes.NUMERIC(10, 2), "primaryKey": True, "autoIncrement": False},
    "TEXTO_ASSINATURA": {"type": DataType.BINARY},
    "ATO_TIPO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ESCREVENTE_ATO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ESCREVENTE_ASSINA_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "LIVRO_ANDAMENTO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "DATA_ABERTURA": {"type": DataType.TIMESTAMP},
    "DATA_LAVRATURA": {"type": DataType.TIMESTAMP},
    "USUARIO_ID": {
        "type": DataTypes.NUMERIC(10, 2),
        "references": {"model": "G_USUARIO", "key": "USUARIO_ID"},
        "onUpdate": "CASCADE",
        "onDelete": "SET NULL",
    },
    "PROTOCOLO": {"type": DataTypes.NUMERIC(10, 2)},
    "ALIENACAO_DATA": {"type": DataType.TIMESTAMP},
    "QUALIFICACAO_IMOVEL_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "FOLHA_INICIAL": {"type": DataTypes.NUMERIC(10, 2)},
    "FOLHA_FINAL": {"type": DataTypes.NUMERIC(10, 2)},
    "FOLHA_TOTAL": {"type": DataTypes.NUMERIC(10, 2)},
    "ALIENACAO_FORMA": {"type": DataTypes.NUMERIC(10, 2)},
    "TEXTO": {"type": DataType.BINARY},
    "TEXTO_FINALIZACAO": {"type": DataType.BINARY},
    "TEXTO_IMOVEL_GERAL": {"type": DataType.BINARY},
    "VALOR_PAGAMENTO": {"type": DataType.DECIMAL},
    "DATA_CANCELAMENTO": {"type": DataType.TIMESTAMP},
    "CANCELADO_DATA": {"type": DataType.TIMESTAMP},
    "CANCELADO_USUARIO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "NATUREZA_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "QTD_IMOVEL": {"type": DataTypes.NUMERIC(10, 2)},
    "HAVIDO_MARCACAO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "SELO_LIVRO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "FONTE_TAMANHO": {"type": DataTypes.NUMERIC(10, 2)},
    "SELO_RECUO": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTIGO_PROTOCOLO": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTERIOR_LIVRO": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTERIOR_TB_CARTORIO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTERIOR_ATO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTERIOR_DATA": {"type": DataType.TIMESTAMP},
    "ATO_ANTERIOR_ANOTACAO_ADICIONAL": {"type": DataType.BINARY},
    "ATO_ANTERIOR_ATO_TIPO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ATO_ANTERIOR_VALOR_DOCUMENTO": {"type": DataType.DECIMAL},
    "FILHO_MAIOR_QTD": {"type": DataTypes.NUMERIC(10, 2)},
    "FILHO_MAIOR_DESCRICAO": {"type": DataType.BINARY},
    "FILHO_MENOR_QTD": {"type": DataTypes.NUMERIC(10, 2)},
    "FILHO_MENOR_DESCRICAO": {"type": DataType.BINARY},
    "CASAMENTO_DATA": {"type": DataType.TIMESTAMP},
    "CASAMENTO_TB_REGIME_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "CENSEC_NATUREZALITIGIO_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "NLOTE": {"type": DataTypes.NUMERIC(10, 2)},
    "CANCELADO_OBSERVACAO": {"type": DataType.STRING},
    "OBSERVACAO": {"type": DataType.STRING},
    "ATO_ANTIGO_OCORRENCIA": {"type": DataType.STRING},
    "ATO_ANTERIOR_OUTORGANTE": {"type": DataType.STRING},
    "ATO_ANTERIOR_OBSERVACAO": {"type": DataType.STRING},
    "FOLHA_LETRA": {"type": DataType.STRING},
    "ATO_ANTIGO": {"type": DataType.STRING},
    "SITUACAO_ATO": {"type": DataType.STRING},
    "GRS_NUMERO": {"type": DataType.STRING},
    "CANCELADO_MOTIVO": {"type": DataType.STRING},
    "ALIENACAO_DATALAVRATURA": {"type": DataType.STRING},
    "MINUTA_PROTEGIDA": {"type": DataType.STRING},
    "USAR_TABELA_AUXILIAR": {"type": DataType.STRING},
    "ATO_ANTERIOR_ORIGEM": {"type": DataType.STRING},
    "ATO_ANTERIOR_FINICIAL": {"type": DataType.STRING},
    "CADASTRAR_IMOVEL": {"type": DataType.STRING},
    "ATO_ANTERIOR_FFINAL": {"type": DataType.STRING},
    "RESP_FILHOS_MAIORES": {"type": DataType.STRING},
    "RESP_FILHOS_MENORES": {"type": DataType.STRING},
    "CENSEC_ACORDO": {"type": DataType.STRING},
    "ESPECIE_PAGAMENTO": {"type": DataType.STRING},
    "FORA_CARTORIO": {"type": DataType.STRING},
    "NFSE_ID": {"type": DataTypes.NUMERIC(10, 2)},
    "ACAO": {"type": DataTypes.NUMERIC(10, 2)},
    "DATA_PROTOCOLO": {"type": DataType.TIMESTAMP},
    "FRENTE_VERSO": {"type": DataType.STRING},
    "LAVRATURA_ONLINE": {"type": DataType.STRING},
    "DATA_PREVISTA_ENTREGA": {"type": DataType.TIMESTAMP},
    "USUARIO_ID_LAVRATURA": {"type": DataTypes.NUMERIC(10, 2)},
    "ATIVO": {"type": DataType.STRING},
    "CONVALIDACAO": {"type": DataType.STRING},
    "LADO_FOLHA_FIM": {"type": DataType.STRING},
    "ATO_ONEROSO": {"type": DataType.STRING},
    "MNE": {"type": DataType.STRING},
    "EH_RESTRITO": {"type": DataType.STRING},
}


def define_t_ato(orm: OriusORM):
    return orm.define(
        "T_ATO",
        T_ATO_ATTRIBUTES,
        {
            "modelName": "T_ATO",
            "tableName": "T_ATO",
            "primaryKey": "ATO_ID",
        },
    )

