import { ColumnOptions, DataType } from '../orm/data-types';
import { orm } from '../orm/client';
import { G_USUARIO } from './G_USUARIO';

export const T_ATO_ATTRIBUTES: Record<string, ColumnOptions> = {
    ATO_ID: {
        type: DataType.BIGINT,
        primaryKey: true,
        autoIncrement: true
    },
    TEXTO_ASSINATURA: { type: DataType.BINARY },
    ATO_TIPO_ID: { type: DataType.BIGINT },
    ESCREVENTE_ATO_ID: { type: DataType.BIGINT },
    ESCREVENTE_ASSINA_ID: { type: DataType.BIGINT },
    LIVRO_ANDAMENTO_ID: { type: DataType.BIGINT },
    DATA_ABERTURA: { type: DataType.TIMESTAMP },
    DATA_LAVRATURA: { type: DataType.TIMESTAMP },
    USUARIO_ID: {
        type: DataType.BIGINT,
        references: {
            model: G_USUARIO,
            key: 'USUARIO_ID'
        },
        onUpdate: 'CASCADE',
        onDelete: 'SET NULL'
    },
    PROTOCOLO: { type: DataType.BIGINT },
    ALIENACAO_DATA: { type: DataType.TIMESTAMP },
    QUALIFICACAO_IMOVEL_ID: { type: DataType.BIGINT },
    FOLHA_INICIAL: { type: DataType.BIGINT },
    FOLHA_FINAL: { type: DataType.BIGINT },
    FOLHA_TOTAL: { type: DataType.BIGINT },
    ALIENACAO_FORMA: { type: DataType.BIGINT },
    TEXTO: { type: DataType.TEXT },
    TEXTO_FINALIZACAO: { type: DataType.TEXT },
    TEXTO_IMOVEL_GERAL: { type: DataType.TEXT },
    VALOR_PAGAMENTO: { type: DataType.DECIMAL },
    DATA_CANCELAMENTO: { type: DataType.TIMESTAMP },
    CANCELADO_DATA: { type: DataType.TIMESTAMP },
    CANCELADO_USUARIO_ID: { type: DataType.BIGINT },
    NATUREZA_ID: { type: DataType.BIGINT },
    QTD_IMOVEL: { type: DataType.BIGINT },
    HAVIDO_MARCACAO_ID: { type: DataType.BIGINT },
    SELO_LIVRO_ID: { type: DataType.BIGINT },
    FONTE_TAMANHO: { type: DataType.BIGINT },
    SELO_RECUO: { type: DataType.BIGINT },
    ATO_ANTIGO_PROTOCOLO: { type: DataType.BIGINT },
    ATO_ANTERIOR_LIVRO: { type: DataType.BIGINT },
    ATO_ANTERIOR_TB_CARTORIO_ID: { type: DataType.BIGINT },
    ATO_ANTERIOR_ATO_ID: { type: DataType.BIGINT },
    ATO_ANTERIOR_DATA: { type: DataType.TIMESTAMP },
    ATO_ANTERIOR_ANOTACAO_ADICIONAL: { type: DataType.TEXT },
    ATO_ANTERIOR_ATO_TIPO_ID: { type: DataType.BIGINT },
    ATO_ANTERIOR_VALOR_DOCUMENTO: { type: DataType.DECIMAL },
    FILHO_MAIOR_QTD: { type: DataType.BIGINT },
    FILHO_MAIOR_DESCRICAO: { type: DataType.TEXT },
    FILHO_MENOR_QTD: { type: DataType.BIGINT },
    FILHO_MENOR_DESCRICAO: { type: DataType.TEXT },
    CASAMENTO_DATA: { type: DataType.TIMESTAMP },
    CASAMENTO_TB_REGIME_ID: { type: DataType.BIGINT },
    CENSEC_NATUREZALITIGIO_ID: { type: DataType.BIGINT },
    NLOTE: { type: DataType.BIGINT },
    CANCELADO_OBSERVACAO: { type: DataType.STRING },
    OBSERVACAO: { type: DataType.STRING },
    ATO_ANTIGO_OCORRENCIA: { type: DataType.STRING },
    ATO_ANTERIOR_OUTORGANTE: { type: DataType.STRING },
    ATO_ANTERIOR_OBSERVACAO: { type: DataType.STRING },
    FOLHA_LETRA: { type: DataType.STRING },
    ATO_ANTIGO: { type: DataType.STRING },
    SITUACAO_ATO: { type: DataType.STRING },
    GRS_NUMERO: { type: DataType.STRING },
    CANCELADO_MOTIVO: { type: DataType.STRING },
    ALIENACAO_DATALAVRATURA: { type: DataType.STRING },
    MINUTA_PROTEGIDA: { type: DataType.STRING },
    USAR_TABELA_AUXILIAR: { type: DataType.STRING },
    ATO_ANTERIOR_ORIGEM: { type: DataType.STRING },
    ATO_ANTERIOR_FINICIAL: { type: DataType.STRING },
    CADASTRAR_IMOVEL: { type: DataType.STRING },
    ATO_ANTERIOR_FFINAL: { type: DataType.STRING },
    RESP_FILHOS_MAIORES: { type: DataType.STRING },
    RESP_FILHOS_MENORES: { type: DataType.STRING },
    CENSEC_ACORDO: { type: DataType.STRING },
    ESPECIE_PAGAMENTO: { type: DataType.STRING },
    FORA_CARTORIO: { type: DataType.STRING },
    NFSE_ID: { type: DataType.BIGINT },
    ACAO: { type: DataType.BIGINT },
    DATA_PROTOCOLO: { type: DataType.TIMESTAMP },
    FRENTE_VERSO: { type: DataType.STRING },
    LAVRATURA_ONLINE: { type: DataType.STRING },
    DATA_PREVISTA_ENTREGA: { type: DataType.TIMESTAMP },
    USUARIO_ID_LAVRATURA: { type: DataType.BIGINT },
    ATIVO: { type: DataType.STRING },
    CONVALIDACAO: { type: DataType.STRING },
    LADO_FOLHA_FIM: { type: DataType.STRING },
    ATO_ONEROSO: { type: DataType.STRING },
    MNE: { type: DataType.STRING },
    EH_RESTRITO: { type: DataType.STRING }
};

export const T_ATO = orm.define('T_ATO', T_ATO_ATTRIBUTES, {
    modelName: 'T_ATO',
    tableName: 'T_ATO',
    primaryKey: 'ATO_ID'
});
